### PR TITLE
fix a bug of  example account.profile.fetch() in  README

### PR DESCRIPTION
**Pull request by ederribeiro**
Fixes the issue #79

### CODE REVIEW

**Comment by gr2m** [comment]
@ederribeiro thanks a lot Eder!

Just one minor thing: could you reword your commit to `docs(README): fix a bug of example account.profile.fetch()`?

**Comment by ederribeiro** [comment]
@gr2m sure!!

**Comment by ederribeiro** [comment]
@gr2m It's done!

**Comment by gr2m** [comment]
Awesome, thanks! 

LGTM

ping @hoodiehq/maintainers for 2nd review :eyes:

**Comment by HipsterBrown** [comment]
Nicely done @ederribeiro! LGTM

Merging asp.

**Pull request merged**
