### PR TITLE
Resolve account.signIn with session instead of account

### PR DESCRIPTION
**Pull request by andru**
I think this takes care of #26. Look OK?

I had to fix the events test too, as it calls the signIn method and plays with the resolved value

### CODE REVIEW

**Comment by gr2m** [comment]
Looks great, thanks Andru! Can you split up the commit messages following our commit conventions, so [semantic-release](https://github.com/semantic-release/semantic-release) can do its magic? I’d split it in 3 commits

1. `test: trigger "signin" event with session properties`
2. `test: resolve .signIn with session properties`
3. `fix: resolve .signIn / trigger "signin" event with session properties

That will make `semantic-release` publish a patch release once all tests pass on travis. 

I can also do it for you, or happy to help if you have any questions on how that works

**Comment by andru** [comment]
@gr2m First time I've done a rebase for a pull request. Look ok?

**Comment by gr2m** [comment]
Perfect :ok_hand: 

Thanks for the great work. I hereby invite you to @hoodiehq/committers :) You got mail

**Comment by nickcolley** [comment]
This is great, nice work @andru :+1: :tada: :100:

**Pull request merged**
