### PR TITLE
WIP: #54 hoodie.account.fetch(), .update(), .profile.fetch() and .profile.update() should fail with UnauthenticatedError if session is invalid, but currently fails with "Not FoundError"

### LINKED ISSUE #54: hoodie.account.fetch(), .update(), .profile.fetch() and .profile.update() should fail with UnauthenticatedError if session is invalid, but currently fails with "Not FoundError"
To simulate an unauthenticated state, replace `session.id` in `localStorage.account` with a bogus value, then reload the page and do `account.fetch()`

---

- [x] claim this issue (@realtin)
- [x] start a PR (#62)
- [x] add unit and integration tests for `account.fetch()`. In the latter, make sure that an "unauthenticate" event gets triggered
- [ ] fix account.fetch()
- [ ] repeat steps for `account.update`, `account.profile.fetch` and `account.profile.update`
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88

### PR DESCRIPTION
**Pull request by Realtin**
closes #54

### CODE REVIEW

**Comment by gr2m** [comment]
@Realtin is this ready for review or are you still working on it?

**Comment by Realtin** [comment]
I'll continue to work on it tonight at nodeschool!

**Comment by Realtin** [comment]
ok, looking over the code and so on. I'm not sure If I should fix it at all since it is just a side effect of using "baseURL" instead of "url" in the options. So it is kind of "erroring" correctly. 
what do you think?

**Comment by gr2m** [comment]
ah so it will be fixed by https://github.com/hoodiehq/hoodie-client-account/issues/64?

**Comment by Realtin** [comment]
yes, I think so.

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-client-account/pull/72

**Pull request closed without merging**
